# Generated by Django 4.0.4 on 2022-04-28 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=20, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=20, verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Ingrese Apellido', max_length=45, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjeria', 'Cédula de Extranjeria')], max_length=21, verbose_name='Tipo Documento')),
                ('Numero_Documento', models.IntegerField(verbose_name='Numero Documento')),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono')),
                ('usuario', models.CharField(blank=True, max_length=20, verbose_name='Usuario')),
                ('contraseña', models.CharField(max_length=45, verbose_name='Contraseña')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('precio_total', models.FloatField(verbose_name='Precio Total')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('Entregad', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Estado')),
                ('observaciones', models.CharField(blank=True, max_length=45, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Ingrese Apellido', max_length=45, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjeria', 'Cédula de Extranjeria')], max_length=21, verbose_name='Tipo Documento')),
                ('Numero_Documento', models.IntegerField(verbose_name='Numero Documento')),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=45, verbose_name='Dirección')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor')], max_length=20, verbose_name='Rol')),
                ('usuario', models.CharField(blank=True, max_length=20, verbose_name='Usuario')),
                ('contraseña', models.CharField(blank=True, max_length=45, verbose_name='Contraseña')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=45, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=45, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono')),
                ('correo', models.EmailField(blank=True, max_length=45, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('Precio_Total', models.FloatField(verbose_name='Precio Total')),
                ('Tipo_Venta', models.CharField(choices=[('local', 'Local'), ('Domicilio', 'Domicilio')], max_length=20, verbose_name='Tipo Venta')),
                ('Iva', models.FloatField(verbose_name='Iva')),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.domicilio', verbose_name='Domicilio')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.empleado', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Nombre', max_length=45, verbose_name='Nombre')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('porcentajeGanancia', models.FloatField(verbose_name='Porcentaje Ganancia')),
                ('unidadMedida', models.CharField(max_length=10, verbose_name='Unidad de Medida')),
                ('stock', models.SmallIntegerField(verbose_name='Stock')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.marca', verbose_name='Marca')),
            ],
        ),
        migrations.AddField(
            model_name='domicilio',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.empleado', verbose_name='Empleado'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
                ('barrio', models.CharField(max_length=20, verbose_name='Barrio')),
                ('municipio', models.CharField(blank=True, max_length=15, verbose_name='Municipio')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('iva', models.FloatField(verbose_name='Iva')),
                ('valor_parcial', models.FloatField(verbose_name='Valor Parcial')),
                ('Metodo_pago', models.CharField(choices=[('Datafono', 'Datafono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transacción')], max_length=20, verbose_name='Metodo Pago')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.venta', verbose_name='Venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('iva', models.FloatField(verbose_name='Iva')),
                ('valor_parcial', models.FloatField(verbose_name='Valor Parcial')),
                ('Metodo_pago', models.CharField(choices=[('Datafono', 'Datafono'), ('Efectivo', 'Efectivo'), ('Transacción', 'Transacción')], max_length=20, verbose_name='Metodo Pago')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.producto', verbose_name='Producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.proveedor', verbose_name='Proveedor'),
        ),
    ]
